### ISSUE TITLE
windows系统网页加载不了资源

### ISSUE THREAD

**Issue by hbgongen** [saltbo/seenvoy#2]
浏览器报错
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by hbgongen** [comment]
请问这个如何解决，linux下倒是可以加载页面

**Comment by hbgongen** [comment]
index.56957fbf.js:183  Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at e (index.56957fbf.js:183:1504)
    at index.56957fbf.js:183:1893

**Comment by hbgongen** [comment]
![image](https://github.com/bonaysoft/seenvoy/assets/36953705/b1b9f281-080c-49c0-9d53-c5aa4348e0e6)

**Comment by saltbo** [comment]
截图的报错应该是你envoy版本太老了，我做这个项目的时候应该是1.20+

**Comment by hbgongen** [comment]
@saltbo 我貌似使用过1.22的版本，好像还是有这个报错，我再试试再联系您。如果您这边有确定的大版本可以告诉我一下。

**Comment by hbgongen** [comment]
感谢您回答

**Comment by hbgongen** [comment]
<img width="683" alt="1692009859006" src="https://github.com/bonaysoft/seenvoy/assets/36953705/e95950c1-4091-43e3-89ae-f47e8d264b1f">
<img width="925" alt="1692009859014" src="https://github.com/bonaysoft/seenvoy/assets/36953705/f7a22b4a-331f-44e8-ad20-246ad4246f5d">
<img width="933" alt="1692009859021" src="https://github.com/bonaysoft/seenvoy/assets/36953705/2f7edcee-1b29-4ce4-80b5-a3f07297ece1">
![1692009859029](https://github.com/bonaysoft/seenvoy/assets/36953705/7aa18019-0658-4c09-acd9-950e541cd6ca)
<img width="933" alt="1692009859036" src="https://github.com/bonaysoft/seenvoy/assets/36953705/0c53e5ae-7dca-4357-9ed3-9b307c642ae1">
<img width="933" alt="1692009859044" src="https://github.com/bonaysoft/seenvoy/assets/36953705/4a4ff14b-2b8a-4d21-8ff6-a1fd795f5a47">
已经使用了1.20+ 1.21+ 1.22+ 1.23+ 1.24+ 1.25+

**Comment by hbgongen** [comment]
均没有成功，是否只能在istio版本才能显示出来？

**Comment by hbgongen** [comment]
@saltbo
